name: Crowdin Upload Only

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  crowdin-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Crowdin CLI
        run: npm install -g @crowdin/cli

      - name: Upload sources to Crowdin
        run: crowdin upload sources
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
