name: Update version badge from Wave

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get latest Wave version from GitHub API
        id: get_wave_version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/LunaStev/Wave/releases | jq -r 'map(select(.prerelease == true or .prerelease == false)) | .[0].tag_name')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate SVG
        run: |
          sed "s/{{VERSION}}/${{ steps.get_wave_version.outputs.version }}/g" img/template.svg > img/version-badge.svg

      - name: Commit and push badge
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add img/version-badge.svg
          git commit -m "Update version badge to ${{ steps.get_wave_version.outputs.version }}"
          git push